name: Python CI

on:
  push:
    branches: [ main, task-1, task-2 ]
  pull_request:
    branches: [ main ]

jobs:
  run-python-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run EDA Script (example)
      run: |
        python scripts/eda_summary.py